services:
  back:
    image: ghcr.io/ofertando-inc/back:prod
    container_name: back-ofertando-prod
    pull_policy: always
    restart: unless-stopped
    ports:
      - '${BACKEND_PORT:-3000}:${PORT:-3000}'
    networks:
      - dokploy-network
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT:-3000}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-1d}
      CORS_ORIGINS: ${CORS_ORIGINS}

networks:
  dokploy-network:
    external: true
